version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      gha-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
