name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NBCONVERT_JOBS: '4'
  LITERATE_PROC: '2'
  EXTRA_ARGS: ''   # Extra arguments for nbconvert
  CACHE_NUM: '3'
  JULIA_CONDAPKG_BACKEND: 'Null'
  JULIA_CI: 'true'
  NBCACHE: '.cache'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      id: cp
      with:
        python-version: '3.x'
    - name: Cache pip dependencies
      uses: actions/cache@v4
      id: cache-py
      with:
        path: ${{ env.pythonLocation }}
        key:  ${{ runner.os }}-pip-${{ steps.cp.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
    - name: Install pip dependencies if cache miss
      if: ${{ steps.cache-py.outputs.cache-hit != 'true' }}
      run: pip install -r requirements.txt
    - name: Cache executed notebooks
      uses: actions/cache@v4
      id: cache-nb
      with:
        path: ${{ env.NBCACHE }}
        key: ${{ runner.os }}-nb-${{ env.CACHE_NUM }}-${{ hashFiles('src/**', 'Project.toml', 'Manifest.toml') }}-${{ hashFiles('docs/**/*.ipynb', 'docs/**/*.jl') }}
        restore-keys: |
          ${{ runner.os }}-nb-${{ env.CACHE_NUM }}-${{ hashFiles('src/**', 'Project.toml', 'Manifest.toml') }}-
    - name: Read Julia version
      uses: SebRollen/toml-action@v1.2.0
      id: read_toml
      with:
        file: 'Manifest.toml'
        field: 'julia_version'
    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ steps.read_toml.outputs.value }}
        show-versioninfo: 'true'
    - name: Restore Julia packages
      uses: actions/cache/restore@v4
      id: cache-julia
      with:
        path: |
          ~/.julia
          !~/.julia/registries
        key: ${{ runner.os }}-julia-${{ env.CACHE_NUM }}-${{ hashFiles('src/**', 'Project.toml', 'Manifest.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-${{ env.CACHE_NUM }}-
    - name: Install Julia packages
      if: ${{ steps.cache-julia.outputs.cache-hit != 'true' }}
      env:
        PYTHON: ${{ env.pythonLocation }}/python
      run: julia --color=yes instantiate.jl
    - name: Save Julia packages
      uses: actions/cache/save@v4
      if: ${{ steps.cache-julia.outputs.cache-hit != 'true' }}
      with:
        path: |
          ~/.julia
          !~/.julia/registries
        key: ${{ steps.cache-julia.outputs.cache-primary-key }}
    - name: Install IJulia kernel and run literate notebooks
      run: julia --color=yes -p ${{ env.LITERATE_PROC }} --heap-size-hint=4G literate.jl
    - name: Execute Jupyter notebooks
      run: >
        parallel -a ipynbs.txt --joblog job.log -j ${{ env.NBCONVERT_JOBS }} jupyter nbconvert --to notebook
        --execute ${{ env.EXTRA_ARGS }}
        --ExecutePreprocessor.timeout=-1
        --ExecutePreprocessor.kernel_name=julia-1.$(julia -e 'print(VERSION.minor)')
        --output ${{ github.workspace }}/${{ env.NBCACHE }}/{}
        {}
    - name: Show GUN parallel execution stats
      run: cat job.log
    - name: Copy back built notebooks
      run: cp --verbose -rf ${{ env.NBCACHE }}/docs/* docs/
    - name: Build website
      run: jupyter-book build docs/
    - name: Upload pages artifact
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html/

  # Deploy pages
  deploy:
    needs: CI
    if: ${{ github.ref == 'refs/heads/main' }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      actions: read   # to download an artifact uploaded by `actions/upload-pages-artifact@v3`
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
