name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/linkcheck.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    env:
      DIR: 'docs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        id: cp
        with:
          python-version: '3.x'
      - name: Cache pip dependencies
        uses: actions/cache@v4
        id: cache-py
        with:
          save-always: 'true'
          path: ${{ env.pythonLocation }}
          key:  ${{ runner.os }}-pip-${{ steps.cp.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
      - name: Install pip dependencies if cache miss
        if: ${{ steps.cache-py.outputs.cache-hit != 'true' }}
        run: pip install -r requirements.txt
      - name: Build website
        run: jupyter-book build ${DIR} --builder linkcheck
